export const events = [
  {
    id: '1',
    title: 'Winter Formal 2024',
    slug: 'winter-formal-2024',
    description: 'Join us for an unforgettable evening at our annual Winter Formal dance.',
    image: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=800',
    date: '2024-12-15',
    time: '19:00',
    location: 'Grand Ballroom, Downtown Montreal',
    organizer: 'MSU Social Committee',
    category: 'Social',
    status: 'upcoming',
    attendees: 245,
    maxAttendees: 300,
  },
  {
    id: '2',
    title: 'Career Fair 2024',
    slug: 'career-fair-2024',
    description: 'Connect with top employers and explore career opportunities in various fields.',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
    date: '2024-11-20',
    time: '10:00',
    location: 'Student Center, Main Hall',
    organizer: 'Career Services',
    category: 'Career',
    status: 'upcoming',
    attendees: 180,
    maxAttendees: 500,
  },
  {
    id: '3',
    title: 'Debate Tournament',
    slug: 'debate-tournament',
    description: 'Annual inter-collegiate debate competition with prizes for top performers.',
    image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800',
    date: '2024-11-25',
    time: '09:00',
    location: 'Auditorium A',
    organizer: 'Debate Club',
    category: 'Academic',
    status: 'upcoming',
    attendees: 64,
    maxAttendees: 100,
  },
  {
    id: '4',
    title: 'Halloween Party',
    slug: 'halloween-party',
    description: 'Costume contest, spooky decorations, and treats for everyone!',
    image: 'https://images.unsplash.com/photo-1509557965875-b88c97052f0e?w=800',
    date: '2024-10-31',
    time: '18:00',
    location: 'Student Lounge',
    organizer: 'Student Life',
    category: 'Social',
    status: 'upcoming',
    attendees: 120,
    maxAttendees: 150,
  },
  {
    id: '5',
    title: 'Science Symposium',
    slug: 'science-symposium',
    description: 'Student research presentations and keynote speakers from leading institutions.',
    image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800',
    date: '2024-12-05',
    time: '13:00',
    location: 'Science Building, Room 101',
    organizer: 'Science Club',
    category: 'Academic',
    status: 'upcoming',
    attendees: 85,
    maxAttendees: 120,
  },
  {
    id: '6',
    title: 'Charity Fundraiser',
    slug: 'charity-fundraiser',
    description: 'Help us raise funds for local community organizations through various activities.',
    image: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=800',
    date: '2024-12-10',
    time: '11:00',
    location: 'Campus Quad',
    organizer: 'Community Service Club',
    category: 'Community',
    status: 'upcoming',
    attendees: 200,
    maxAttendees: 300,
  },
]

export const petitions = [
  {
    id: '1',
    title: 'Extend Library Hours During Finals',
    slug: 'extend-library-hours-finals',
    summary: 'Request to extend library operating hours until midnight during final exam period.',
    description: 'Many students study late into the night during finals week. Currently, the library closes at 10 PM, which limits study options for students who prefer to study in a quiet environment. We propose extending hours until midnight during the two-week final exam period each semester.',
    category: 'Facilities',
    author: 'Sarah Chen',
    authorId: 'user1',
    status: 'Open',
    supporters: 342,
    targetSupporters: 500,
    createdAt: '2024-10-15',
    comments: [
      {
        id: 'c1',
        author: 'Michael Brown',
        content: 'This would be incredibly helpful for students who work part-time jobs during the day.',
        createdAt: '2024-10-16',
      },
      {
        id: 'c2',
        author: 'Emma Wilson',
        content: 'I fully support this. The library is the best place to focus during finals.',
        createdAt: '2024-10-17',
      },
    ],
  },
  {
    id: '2',
    title: 'More Vegetarian Options in Cafeteria',
    slug: 'more-vegetarian-options-cafeteria',
    summary: 'Increase the variety and quality of vegetarian and vegan meal options.',
    description: 'The current vegetarian options in our cafeteria are limited and often repetitive. We request a wider variety of plant-based meals that are nutritious, delicious, and sustainable. This would benefit not only vegetarians and vegans but also students looking to reduce their meat consumption for environmental reasons.',
    category: 'Food Services',
    author: 'Alex Rivera',
    authorId: 'user2',
    status: 'Under Review',
    supporters: 189,
    targetSupporters: 300,
    createdAt: '2024-10-10',
    comments: [
      {
        id: 'c3',
        author: 'Jordan Lee',
        content: 'Great initiative! More plant-based options would be amazing.',
        createdAt: '2024-10-11',
      },
    ],
  },
  {
    id: '3',
    title: 'Install Water Bottle Refill Stations',
    slug: 'install-water-bottle-refill-stations',
    summary: 'Install filtered water bottle refill stations throughout campus buildings.',
    description: 'To promote sustainability and reduce plastic waste, we propose installing water bottle refill stations on each floor of every academic building. These stations would provide filtered water and encourage students to use reusable bottles.',
    category: 'Sustainability',
    author: 'Taylor Kim',
    authorId: 'user3',
    status: 'Approved',
    supporters: 456,
    targetSupporters: 400,
    createdAt: '2024-09-20',
    comments: [],
  },
  {
    id: '4',
    title: 'Create Student Study Lounge',
    slug: 'create-student-study-lounge',
    summary: 'Establish a dedicated 24/7 study lounge with comfortable seating and outlets.',
    description: 'Students need a space to study at any hour. We propose converting an unused room into a 24/7 study lounge with comfortable seating, ample electrical outlets, good lighting, and quiet zones.',
    category: 'Facilities',
    author: 'Chris Johnson',
    authorId: 'user4',
    status: 'Open',
    supporters: 278,
    targetSupporters: 400,
    createdAt: '2024-10-20',
    comments: [
      {
        id: 'c4',
        author: 'Jamie Park',
        content: 'This would be a game-changer for students with different study schedules.',
        createdAt: '2024-10-21',
      },
    ],
  },
  {
    id: '5',
    title: 'Increase Mental Health Resources',
    slug: 'increase-mental-health-resources',
    summary: 'Expand counseling services and reduce wait times for appointments.',
    description: 'Mental health support is crucial for student success. We request increased funding for counseling services, more counselors on staff, and reduced wait times for appointments. Additionally, we propose workshops on stress management and mental wellness.',
    category: 'Student Services',
    author: 'Morgan Williams',
    authorId: 'user5',
    status: 'Implemented',
    supporters: 512,
    targetSupporters: 500,
    createdAt: '2024-08-15',
    comments: [],
  },
]

export const clubs = [
  {
    id: '1',
    name: 'Debate Club',
    description: 'Develop your public speaking and critical thinking skills through competitive debate. We participate in inter-collegiate tournaments and host weekly practice sessions.',
    category: 'Academic',
    president: 'David Chen',
    email: 'debate@msu.edu',
    members: 45,
    meetingTime: 'Wednesdays at 5 PM',
    image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=400',
  },
  {
    id: '2',
    name: 'Environmental Action Club',
    description: 'Work towards a more sustainable campus and community. We organize clean-ups, awareness campaigns, and sustainability initiatives.',
    category: 'Activism',
    president: 'Emma Green',
    email: 'environment@msu.edu',
    members: 62,
    meetingTime: 'Mondays at 4 PM',
    image: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=400',
  },
  {
    id: '3',
    name: 'Photography Club',
    description: 'Explore the art of photography through workshops, photo walks, and exhibitions. All skill levels welcome!',
    category: 'Arts',
    president: 'Sophie Martinez',
    email: 'photo@msu.edu',
    members: 38,
    meetingTime: 'Fridays at 3 PM',
    image: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=400',
  },
  {
    id: '4',
    name: 'Chess Club',
    description: 'Whether you are a beginner or a grandmaster, join us for friendly games and competitive tournaments.',
    category: 'Recreation',
    president: 'Alex Petrov',
    email: 'chess@msu.edu',
    members: 28,
    meetingTime: 'Tuesdays at 6 PM',
    image: 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=400',
  },
  {
    id: '5',
    name: 'Model United Nations',
    description: 'Simulate UN committees and develop diplomatic skills. We attend conferences across North America.',
    category: 'Academic',
    president: 'Rachel Kim',
    email: 'mun@msu.edu',
    members: 55,
    meetingTime: 'Thursdays at 5 PM',
    image: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=400',
  },
  {
    id: '6',
    name: 'Music Society',
    description: 'For musicians and music lovers alike. We organize concerts, jam sessions, and open mic nights.',
    category: 'Arts',
    president: 'Marcus Johnson',
    email: 'music@msu.edu',
    members: 72,
    meetingTime: 'Saturdays at 2 PM',
    image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=400',
  },
  {
    id: '7',
    name: 'Coding Club',
    description: 'Learn to code, work on projects, and participate in hackathons. All experience levels welcome.',
    category: 'Technology',
    president: 'Kevin Zhang',
    email: 'coding@msu.edu',
    members: 89,
    meetingTime: 'Wednesdays at 6 PM',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400',
  },
  {
    id: '8',
    name: 'Dance Club',
    description: 'Express yourself through dance! We offer classes in various styles and perform at campus events.',
    category: 'Arts',
    president: 'Isabella Torres',
    email: 'dance@msu.edu',
    members: 67,
    meetingTime: 'Mondays and Wednesdays at 7 PM',
    image: 'https://images.unsplash.com/photo-1508700929628-666bc8bd84ea?w=400',
  },
]

export const sponsors = [
  {
    id: '1',
    name: 'TechCorp Industries',
    logo: 'https://via.placeholder.com/200x80?text=TechCorp',
    tier: 'Platinum',
    description: 'Leading technology company supporting student innovation.',
    contribution: 15000,
    website: 'https://example.com/techcorp',
  },
  {
    id: '2',
    name: 'Green Energy Solutions',
    logo: 'https://via.placeholder.com/200x80?text=GreenEnergy',
    tier: 'Gold',
    description: 'Committed to sustainable energy and environmental initiatives.',
    contribution: 10000,
    website: 'https://example.com/greenenergy',
  },
  {
    id: '3',
    name: 'Local Bank & Trust',
    logo: 'https://via.placeholder.com/200x80?text=LocalBank',
    tier: 'Gold',
    description: 'Your community bank supporting local education.',
    contribution: 8000,
    website: 'https://example.com/localbank',
  },
  {
    id: '4',
    name: 'City Bookstore',
    logo: 'https://via.placeholder.com/200x80?text=CityBooks',
    tier: 'Silver',
    description: 'Independent bookstore serving the student community.',
    contribution: 3000,
    website: 'https://example.com/citybooks',
  },
  {
    id: '5',
    name: 'Campus Coffee Co.',
    logo: 'https://via.placeholder.com/200x80?text=CampusCoffee',
    tier: 'Silver',
    description: 'Fueling students with quality coffee since 2010.',
    contribution: 2500,
    website: 'https://example.com/campuscoffee',
  },
  {
    id: '6',
    name: 'Student Pizza Place',
    logo: 'https://via.placeholder.com/200x80?text=StudentPizza',
    tier: 'Bronze',
    description: 'Best pizza deals for students in the area.',
    contribution: 1000,
    website: 'https://example.com/studentpizza',
  },
]

export const financeRecords = [
  {
    id: '1',
    type: 'income',
    category: 'Sponsorship',
    description: 'TechCorp Industries - Annual Sponsorship',
    amount: 15000,
    date: '2024-09-01',
    status: 'Received',
  },
  {
    id: '2',
    type: 'expense',
    category: 'Events',
    description: 'Winter Formal - Venue Rental',
    amount: 3500,
    date: '2024-10-15',
    status: 'Paid',
  },
  {
    id: '3',
    type: 'expense',
    category: 'Clubs',
    description: 'Debate Club - Tournament Registration',
    amount: 500,
    date: '2024-10-20',
    status: 'Paid',
  },
  {
    id: '4',
    type: 'income',
    category: 'Fundraiser',
    description: 'Charity Fundraiser Proceeds',
    amount: 2500,
    date: '2024-10-25',
    status: 'Received',
  },
  {
    id: '5',
    type: 'expense',
    category: 'Equipment',
    description: 'Sound System for Events',
    amount: 1200,
    date: '2024-11-01',
    status: 'Pending',
  },
]

export const reimbursements = [
  {
    id: '1',
    requester: 'Emma Green',
    club: 'Environmental Action Club',
    description: 'Supplies for campus cleanup event',
    amount: 150,
    date: '2024-10-18',
    status: 'Approved',
    receiptUrl: '/receipts/cleanup.pdf',
  },
  {
    id: '2',
    requester: 'David Chen',
    club: 'Debate Club',
    description: 'Travel expenses for tournament',
    amount: 280,
    date: '2024-10-22',
    status: 'Pending',
    receiptUrl: '/receipts/travel.pdf',
  },
  {
    id: '3',
    requester: 'Sophie Martinez',
    club: 'Photography Club',
    description: 'Printing costs for exhibition',
    amount: 95,
    date: '2024-10-25',
    status: 'Paid',
    receiptUrl: '/receipts/printing.pdf',
  },
]

export const budgetRequests = [
  {
    id: '1',
    club: 'Music Society',
    description: 'New instruments for practice room',
    amount: 2000,
    date: '2024-10-20',
    status: 'Approved',
  },
  {
    id: '2',
    club: 'Coding Club',
    description: 'Hackathon prize sponsorship',
    amount: 500,
    date: '2024-10-28',
    status: 'Pending',
  },
  {
    id: '3',
    club: 'Dance Club',
    description: 'Costumes for spring performance',
    amount: 800,
    date: '2024-11-01',
    status: 'Pending',
  },
]

export const users = [
  {
    id: 'admin1',
    name: 'Admin User',
    email: 'admin@msu.edu',
    role: 'admin',
  },
  {
    id: 'user1',
    name: 'Sarah Chen',
    email: 'sarah.chen@marianopolis.edu',
    role: 'student',
  },
  {
    id: 'user2',
    name: 'Alex Rivera',
    email: 'alex.rivera@marianopolis.edu',
    role: 'student',
  },
]
